---
- name: Download and execute k3s install script using calico as a CNI  
  shell: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-backend=none --cluster-cidr=192.168.0.0/16 --disable-network-policy --disable=traefik --node-ip {{ ansible_facts.enp0s8.ipv4.address }}" sh -

- name: Install the Calico operator and custom resource definitions
  shell: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

- name: Install Calico by creating the necessary custom resource
  shell: kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml

