---
- name: Install kubeadm
  hosts: all
  become: true
  tasks:
    - name: Disable swapoff
      command: swapoff -a
    - name: Prevent swap from turning on after reboots by commenting it in the /etc/fstab file
      command: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Let iptables see bridged traffic
      community.general.modprobe:
          name: br_netfilter
          state: present

    - name: Load overlay module
      community.general.modprobe:
          name: overlay
          state: present

    - name: Load overlay and br_netfilter after reboot
      blockinfile:
        path: /etc/modules-load.d/containerd.conf
        create: true
        block: |
          overlay
          br_netfilter

    # Install containerd
    - name: Setup required sysctl params, these persist across reboots
      blockinfile:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        create: true
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply sysctl params without reboot
      command: sysctl --system

    - name: Install containerd
      apt:
        name: containerd
        state: present
        update_cache: yes

    # Configure containerd:
    - name: create directory
      file:
        path: /etc/containerd
        state: directory

    - name:
      shell: containerd config default | sudo tee /etc/containerd/config.toml

    - name: restart containerd
      systemd:
        state: restarted
        daemon_reload: yes
        name: containerd

    # Installing kubeadm, kubelet and kubectl 
    - name: install packages needed to use the Kubernetes apt repository
      apt:
        state: present
        pkg:
         - apt-transport-https
         - ca-certificates
         - curl

    - name: download the Google Cloud public signing key
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg

    - name: add the Kubernetes apt repository
      shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list

    - name: install kubeadm, kubelet, kubectl
      apt:
        state: present
        update_cache: yes
        pkg:
          - kubelet
          - kubeadm
          - kubectl


- name: Initialize kubeadm cluster
  hosts: master
  become: true
  tasks:
    - include_tasks: flannel.yaml
      when: cni == "flannel"

    - include_tasks: calico.yaml
      when: cni == "calico"


- name: Join cluster
  hosts: worker
  become: true
  vars:
    kubeadm_join_command: "{{ lookup('file', 'kubeadm_joind.sh') }}"
  tasks:
    - debug: msg="{{ kubeadm_join_command | replace('\\\n\t', ' ')}}"

    - name: Execute join command
      command: "{{ kubeadm_join_command | replace('\\\n\t', ' ') }}"
      register: join_command_output

    - debug: msg="{{ join_command_output.stdout_lines }}"

- name: Change the internal IP of Kubernetes nodes (Problem only with VirtualBox that sets node ip to first interface 10.0.2.15)
  hosts: all
  become: true
  tasks:
    - name: Add --node [IP] to KUBELET_KUBECONFIG_ARGS in 10-kubeadm.conf
      lineinfile:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        regex: "^Environment=\"KUBELET_KUBECONFIG_ARGS"
        line: "Environment=\"KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --node-ip {{ ansible_facts.enp0s8.ipv4.address }} \""

    - name: Restart kubelet
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet
